version: "3.9"
services:
  web:
    build: .
      # context: .
      # dockerfile: Dockerfile
      # image: 'dude/man:v2'
    image: 'sandbox'
    volumes:
      - ".:/app"
    ports:
      - "8900:8900"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    command: sh -c "npm install && npm run dev"